server.port=8081

estatistica.janela-segundos=60

spring.jackson.deserialization.fail-on-unknown-properties=false

spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
springjackson.time-zone=UTC

management.endpoints.web.exposure.include=health,info,metrics
management.info.env.enable=true

info.app.name=Transacao API
info.app.description=Desafio Backend Itaú Unibanco
info.app.version=1.0.0

logging.level.br.com.itau=DEBUG
